CREATE USER addrmon IDENTIFIED BY "addrmon";

GRANT resource,connect,dba to addrmon;

select ts.ts#,ts.name,df.file#,df.name, df.BYTES/POWER(2,30) GBytes
FROM v$tablespace ts LEFT OUTER JOIN v$datafile df ON ts.TS# = df.TS#;


CREATE TABLESPACE ADDR_DATA_SPACE
DATAFILE 'C:\ORACLEXE\APP\ORACLE\ORADATA\XE\ADDRDATAFILE.DBF' SIZE 50M
     AUTOEXTEND ON NEXT 1M MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL
BLOCKSIZE 8K
 ONLINE LOGGING
 SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE ADDR_INDEX_SPACE
DATAFILE 'C:\ORACLEXE\APP\ORACLE\ORADATA\XE\ADDRINDEXFILE.DBF' SIZE 50M
	 AUTOEXTEND ON NEXT 1M MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL
BLOCKSIZE 8K
 ONLINE LOGGING
 SEGMENT SPACE MANAGEMENT AUTO;

select * FROM v$tablespace;

SELECT * FROM v$datafile;

select ts.ts#,ts.name,df.file#,df.name, df.BYTES/POWER(2,30) GBytes
FROM v$tablespace ts LEFT OUTER JOIN v$datafile df ON ts.TS# = df.TS#;
